# Assignment 5 submission: Language Modeling & Recurrent Neural Networks

## Group members: Divya Sasidharan, Poornima Venkatesha, Sinchana Eshwarappa Prameela

In [0]:
%tensorflow_version 2.x

In [0]:
from google.colab import drive; drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import os
os.getcwd()

'/content'

In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt


In [0]:
!pip install ipython-autotime
%load_ext autotime

  Created wheel for ipython-autotime: filename=ipython_autotime-0.1-cp36-none-any.whl size=1832 sha256=fb4451f36bf16f88d77268139417d86e89c43506e7425786c9842f1d01d4fdbc
  Stored in directory: /root/.cache/pip/wheels/d2/df/81/2db1e54bc91002cec40334629bc39cfa86dff540b304ebcd6e
Successfully built ipython-autotime


In [0]:
!python prepare_data.py shakespeare_input.txt skp

2020-05-24 20:56:25.836642: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Split input into 22981 sequences...
Serialized 100 sequences...
Serialized 200 sequences...
Serialized 300 sequences...
Serialized 400 sequences...
Serialized 500 sequences...
Serialized 600 sequences...
Serialized 700 sequences...
Serialized 800 sequences...
Serialized 900 sequences...
Serialized 1000 sequences...
Serialized 1100 sequences...
Serialized 1200 sequences...
Serialized 1300 sequences...
Serialized 1400 sequences...
Serialized 1500 sequences...
Serialized 1600 sequences...
Serialized 1700 sequences...
Serialized 1800 sequences...
Serialized 1900 sequences...
Serialized 2000 sequences...
Serialized 2100 sequences...
Serialized 2200 sequences...
Serialized 2300 sequences...
Serialized 2400 sequences...
Serialized 2500 sequences...
Serialized 2600 sequences...
Serialized 2700 sequences...
Serialized 2800 sequences...
Serialized 2900

In [0]:
from prepare_data import parse_seq
import pickle

sequence_length=200


data = tf.data.TFRecordDataset("skp.tfrecords")
#print(data)

data = data.map(lambda x: parse_seq(x, sequence_length))
print(data)
BATCH_SIZE = 128
BUFFER_SIZE = 50000
data = data.shuffle(BUFFER_SIZE).batch(BATCH_SIZE).repeat()
# a map from characters to indices
vocab = pickle.load(open("skp_vocab", mode="rb"))
vocab_size = len(vocab)
# inverse mapping: indices to characters
ind_to_ch = {ind: ch for (ch, ind) in vocab.items()}

print(vocab)
print(vocab_size)
print(ind_to_ch)

<MapDataset shapes: (200,), types: tf.int32>
{'\n': 1, 'u': 2, 'a': 3, 'K': 4, '3': 5, 'C': 6, 'y': 7, 'V': 8, 'U': 9, 'b': 10, '!': 11, 'g': 12, 'B': 13, 'd': 14, 'w': 15, 'n': 16, 'E': 17, 'P': 18, '-': 19, ';': 20, 'D': 21, 'J': 22, 'k': 23, 't': 24, 'G': 25, 'o': 26, 'c': 27, 'm': 28, 'X': 29, 'M': 30, 'v': 31, 'R': 32, 'h': 33, 'r': 34, 'l': 35, 'O': 36, 'x': 37, 'S': 38, 'N': 39, 'T': 40, ' ': 41, '.': 42, "'": 43, 'Z': 44, '?': 45, 'p': 46, '&': 47, '$': 48, ']': 49, 'A': 50, 'Q': 51, ':': 52, 's': 53, 'Y': 54, 'H': 55, 'f': 56, 'L': 57, ',': 58, 'q': 59, 'e': 60, 'F': 61, 'I': 62, '[': 63, 'i': 64, 'W': 65, 'z': 66, 'j': 67, '<S>': 0}
68
{1: '\n', 2: 'u', 3: 'a', 4: 'K', 5: '3', 6: 'C', 7: 'y', 8: 'V', 9: 'U', 10: 'b', 11: '!', 12: 'g', 13: 'B', 14: 'd', 15: 'w', 16: 'n', 17: 'E', 18: 'P', 19: '-', 20: ';', 21: 'D', 22: 'J', 23: 'k', 24: 't', 25: 'G', 26: 'o', 27: 'c', 28: 'm', 29: 'X', 30: 'M', 31: 'v', 32: 'R', 33: 'h', 34: 'r', 35: 'l', 36: 'O', 37: 'x', 38: 'S', 39: 'N', 40

In [0]:
# view data
print(data)
for index ,value in enumerate(data): 
  print(index) 
  print(value.shape)
  print("----example sentence in index-----")
  print(value[0])
  vector=tf.one_hot(value,vocab_size)  
  s=[]
  sentence=""
  for i in value[0].numpy():     
    s.append(ind_to_ch[i])
  print("----example sentence-----")
  print(sentence.join(s))
  print("----vector representation-----")
  print(vector)
  break
  

<RepeatDataset shapes: (None, 200), types: tf.int32>
0
(128, 200)
----example sentence in index-----
tf.Tensor(
[ 0 57 38 40 50 61 61 52  1 30 64 53 24 34 60 53 53 41 61 26 34 14 58 41
 10  7 41 28  7 41 24 34 26 24 33 58 41  7 26  2 41  3 34 60 41 31 60 34
  7 41 15 60 35 35 41 28 60 24 52  1 10  7 41  7 26  2 34 41 35 60  3 31
 60 58 41 12 26 26 14 41 28 64 53 24 34 60 53 53 42  1  1 18 50 25 17 52
  1 65 64 56 60 58 41 10 64 14 41 24 33 60 53 60 41 12 60 16 24 35 60 28
 60 16 41 15 60 35 27 26 28 60 42 41  6 26 28 60 58 41 15 60 41 33  3 31
 60 41  3  1 33 26 24 41 31 60 16 64 53 26 16 41 46  3 53 24  7 41 24 26
 41 14 64 16 16 60 34 52 41 27 26 28 60 58 41 12 60 16 24 35 60 28 60 16
 58 41 62 41 33 26 46 60], shape=(200,), dtype=int32)
----example sentence-----
<S>LSTAFF:
Mistress Ford, by my troth, you are very well met:
by your leave, good mistress.

PAGE:
Wife, bid these gentlemen welcome. Come, we have a
hot venison pasty to dinner: come, gentlemen, I hope
----vector representa

In [0]:
init=tf.keras.initializers.GlorotUniform()
x=tf.Variable(init([68,512]))
y=tf.Variable(init([512,512]))

print(x)
print(y)
print(tf.matmul(x,y))

<tf.Variable 'Variable:0' shape=(68, 512) dtype=float32, numpy=
array([[ 0.00993611, -0.02615932,  0.02099883, ...,  0.01232596,
        -0.02640367,  0.04674964],
       [ 0.04844298,  0.09384456, -0.02246771, ...,  0.00501551,
         0.07491494,  0.0732724 ],
       [-0.0874153 , -0.04493261,  0.07449607, ..., -0.08990824,
        -0.03436653, -0.03187849],
       ...,
       [ 0.08851036,  0.05935428, -0.00863193, ...,  0.07777705,
         0.03478342,  0.03632151],
       [ 0.06806874, -0.08718722,  0.03238624, ...,  0.0445128 ,
         0.00836727,  0.00430316],
       [-0.00315545,  0.00741589,  0.06568872, ...,  0.03165784,
         0.07613265, -0.02535073]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(512, 512) dtype=float32, numpy=
array([[ 0.0664966 ,  0.05369394,  0.07639772, ...,  0.00291781,
         0.0308578 ,  0.0077654 ],
       [-0.02979588,  0.0265544 , -0.06521568, ..., -0.03492369,
        -0.05083403,  0.05136079],
       [ 0.00974547,  0.04228942,  0.01687

In [0]:
#parameter initialisation              
hidden_dim = 512         
"""
U is the weight matrix for weights between input and hidden layers
W is the weight matrix for shared weights in the RNN layer (hidden layer)
V is the weight matrix for weights between hidden and output layers
"""
init=tf.keras.initializers.GlorotUniform()
U=tf.Variable(init([vocab_size,hidden_dim]))
W=tf.Variable(init([hidden_dim,hidden_dim]))
b_W=tf.Variable(tf.zeros([hidden_dim]))

V=tf.Variable(init([hidden_dim,vocab_size]))
b_V=tf.Variable(tf.zeros([vocab_size]))

parameters=[U,W,b_W,V,b_V]
optimizer = tf.keras.optimizers.Adam()

# start training using Gradient Tape
@tf.function
def train_step(input):
  length=input.shape[1]-1 #length is 199 after removing <s>
  with tf.GradientTape() as tape:
    # During forward propagation we save all hidden states in h because need them later.
    # We add one additional element for the initial hidden, which we set to 0     
    h=tf.zeros([input.shape[0],hidden_dim])    
    loss=tf.TensorArray(tf.float32,size=length )            
    for t in tf.range(length):
      current_char=input[:,t]
      next_char=input[:,t+1]
      vector=tf.one_hot(current_char,vocab_size)      
      a=tf.matmul(h,W)+tf.matmul(vector,U)+b_W
      h=tf.nn.tanh(a)      
      c=tf.matmul(h,V)+b_V      
      #o=tf.nn.softmax(c) 
      loss_t=tf.nn.sparse_softmax_cross_entropy_with_logits(next_char,c)      
      #loss=loss+loss_t 
      loss=loss.write(t,loss_t)      
    #loss=loss/(tf.cast(length,tf.float32)) 
    loss=loss.stack()    
    final_loss=tf.reduce_mean(loss)    
  gradients = tape.gradient(final_loss, parameters)
  grads, _ = tf.clip_by_global_norm(gradients,1)# gradient clipping  
  optimizer.apply_gradients(zip(grads, parameters))  
  return final_loss

time: 54.9 ms


In [0]:
steps = 3000
#start of training

for index ,value in enumerate(data):    
  loss=train_step(value)    
  if not index % 500 :   
    print(index, loss)
        
  if index >= steps:
    break

0 tf.Tensor(4.236715, shape=(), dtype=float32)
500 tf.Tensor(2.0259883, shape=(), dtype=float32)
1000 tf.Tensor(1.7993593, shape=(), dtype=float32)
1500 tf.Tensor(1.6732452, shape=(), dtype=float32)
2000 tf.Tensor(1.6013917, shape=(), dtype=float32)
2500 tf.Tensor(1.5523757, shape=(), dtype=float32)
3000 tf.Tensor(1.4987805, shape=(), dtype=float32)
time: 13min 23s


In [0]:
start = 'l'
start_index = [vocab[start]]
print(start_index)
h_t=tf.zeros([1,hidden_dim])
for i in range(2000):
  h_t=tf.nn.tanh(tf.matmul(tf.one_hot(start_index[-1:], depth = vocab_size), U) + tf.matmul(h_t, W) + b_W)#each iteration take the last char
  o_t=tf.nn.softmax(tf.matmul(h_t,V)+b_V).numpy()[0]
  start_index.append(np.random.choice(vocab_size, p = o_t))
text="".join([ind_to_ch[i] for i in start_index])
print(text)


[35]
lifb?
Is told this knightly which of may say!
Teed loat of life me beak your hours for for,
As the sexty shall were wish theas it that
drunches hath her hand: come tewors it.

BYoS:
My goodngs, you wartints, thene of prood so
fromath of thee, that his it, if it what speak these
The devell are alme bying us lards in overtanen
To husband dream his great I think, I lises:
Or the matter, this is the love.
Beloved your soulp: at leads her as here?

IAGO:
Why, then the nightyes on a shall I well,
That brow somethurs; the rangle abort
With we here their reamon see her. Be with the woild:
For mine own his father: were his feer,
Let us on our perfeats with her concerishal's coupted!
Buck'd. I mesir, 'tis born, I lade thee any toound,
To would therefore here in the epitior.
But that omblice, to thine tridune dalkesion lays
Theigh abood, and my lord of Godging of her;
And heremin's beg's in pleise it uidest doge,
The youtorm of their lording core. This griefs again?

FALSTAFF:
The peoplous s

In [0]:
s=tf.zeros([1,hidden_dim])
gen_text=[35] # start character is "l"
ouput_sentence=""
for i in range(500):
  next_input = tf.one_hot(gen_text[-1:],depth=vocab_size)
  a_t=tf.matmul(next_input,U)+tf.matmul(s,W)+b_W
  s=tf.nn.tanh(a_t)      
  c_t=tf.matmul(s,V)+b_V      
  o_t=tf.nn.softmax(c_t).numpy()[0]
  preds =np.random.choice(vocab_size,p=o_t)
  gen_text.append(preds)
ouput_sentence="".join([ind_to_ch[index] for index in gen_text])
print(ouput_sentence)


lo.

KENT:
What you can laid, hell to here a gracious.

BAPTISTO:
My should
we part, as thy paperterrest dode.

NERLON:
Become lockshil: there are shilla? keep these stus
Abswerk offines is thee all me?

BORANAMLCH:
Why, follow! thind I tous it,
Till the would leave a shapping.

BIRON:
RGial, seek, sit soet!
Their stillits to his pronstert.

Second Lendse:
Mest gentle esent; forswer'd me for swear-lehs,
Your gone and friendst lee him wited me!

DO PEMy:
Nawe, I do not the rive of now I hate not,

time: 756 ms


In [0]:
start = 3
limit = 18
delta = 3
for i in range(start, limit, delta):
  print(i)


for j in tf.range(start, limit, delta):
  print(j)

"""
TensorFlow will only capture for loops that iterate over a tensor or a Dataset. So
make sure you use for i in tf.range(10) rather than for i in range(10), or
else the loop will not be captured in the graph. Instead, it will run during tracing.
This may be what you want, if the for loop is meant to build the graph, for example
to create each layer in a neural network.
"""

3
6
9
12
15
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)


'\nTensorFlow will only capture for loops that iterate over a tensor or a Dataset. So\nmake sure you use for i in tf.range(10) rather than for i in range(10), or\nelse the loop will not be captured in the graph. Instead, it will run during tracing.\nThis may be what you want, if the for loop is meant to build the graph, for example\nto create each layer in a neural network.\n'

time: 21.8 ms
