# Assignment 7 submission: Assorted Programming Puzzles

## Group members: Divya Sasidharan, Poornima Venkatesha, Sinchana Eshwarappa Prameela

### 1) Given a 2D tensor of shape (?, n), extract the k (k <= n) highest values for each row into a tensor of shape (?, k). Hint: There might be a function to get the “top k” values of a tensor.

In [0]:
import tensorflow as tf
import numpy as np

# 2D Tensor (matrix)
tensor_2D = np.array([[50, 100, 300,299],  # row 1
                      [256, 356, 389,200],  # row 2
                      [100, 300, 200,200], #row 3
                      [167, 899,100,200]])  # row 4
print("input tensor shape is {}".format(tensor_2D.shape))
print("2D Tensor:\n{}".format(tensor_2D))
print("Tensor dimensions: {}".format(tensor_2D.ndim))
kvalue=tensor_2D.shape[0] -1
top_K=tf.math.top_k(tensor_2D, k=kvalue, sorted=True, name="topK").values
print(" new 2D Tensor of shape {} with {} highest values for each row:\n{}".format(top_K.shape,kvalue,top_K))



print('-----with decorator------')
@tf.function
def example_1(tensor_in):
  print("input tensor shape is {}".format(tensor_2D.shape))
  print("2D Tensor:\n{}".format(tensor_2D))
  print("Tensor dimensions: {}".format(tensor_2D.ndim))
  kvalue=tensor_2D.shape[0] -1
  top_K=tf.math.top_k(tensor_2D, k=kvalue, sorted=True, name="topK").values
  print(" new 2D Tensor of shape {} with {} highest values for each row:\n{}".format(top_K.shape,kvalue,top_K))
  return top_K
example_1(tensor_2D)


input tensor shape is (4, 4)
2D Tensor:
[[ 50 100 300 299]
 [256 356 389 200]
 [100 300 200 200]
 [167 899 100 200]]
Tensor dimensions: 2
 new 2D Tensor of shape (4, 3) with 3 highest values for each row:
[[300 299 100]
 [389 356 256]
 [300 200 200]
 [899 200 167]]
-----with decorator------
input tensor shape is (4, 4)
2D Tensor:
[[ 50 100 300 299]
 [256 356 389 200]
 [100 300 200 200]
 [167 899 100 200]]
Tensor dimensions: 2
 new 2D Tensor of shape (4, 3) with 3 highest values for each row:
Tensor("topK:0", shape=(4, 3), dtype=int64)


<tf.Tensor: shape=(4, 3), dtype=int64, numpy=
array([[300, 299, 100],
       [389, 356, 256],
       [300, 200, 200],
       [899, 200, 167]])>

### 2) Given a tensor of shape (?, n), find the argmax in each row and return a new tensor that contains a 1 in each of the argmax’ positions, and 0s everywhere else.

In [0]:
import tensorflow as tf
import numpy as np

# 2D Tensor (matrix)
tensor_2D = np.array([[50, 100, 300,2990,5],  # row 1
                      [256, 356, 389,200,6],  # row 2
                      [100, 300, 200,200,7], #row 3
                      [1067, 899,100,200,0]])  # row 4
updates_final=[]
for n in range(len(tensor_2D)):  
  updates = [0]*len(tensor_2D[n])
  updates[tf.math.argmax(tensor_2D[n]).numpy()]=1  
  updates_final.append(updates)
final_tensor=tf.convert_to_tensor(updates_final)
print(tensor_2D)
print(final_tensor)

[[  50  100  300 2990    5]
 [ 256  356  389  200    6]
 [ 100  300  200  200    7]
 [1067  899  100  200    0]]
tf.Tensor(
[[0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]], shape=(4, 5), dtype=int32)


### 3)As in 1., but instead of “extracting” the top k values, create a new tensor with shape (?, n) where all but the top k values for each row are zero. Try doing this with a 1D tensor of shape (n,) (i.e. one row) first. Getting it right for a 2D tensor is more tricky; consider this a bonus. Hint: You should look for a way to “scatter” a tensor of values into a different tensor. For two or more dimensions, you need to think carefully about the indices.

In [0]:
import tensorflow as tf
import numpy as np

# 1D Tensor (matrix)
tensor_1D = np.array([50, 100, 300,2990])
print("input tensor shape is {}".format(tensor_1D.shape))
print("1D Tensor:\n{}".format(tensor_1D))
print("Tensor dimensions: {}".format(tensor_1D.ndim))
kvalue=tensor_1D.shape[0] -1
top_K=tf.math.top_k(tensor_1D, k=kvalue, sorted=True, name="topK").values
print(" new 1D Tensor of shape {} with {} highest values for each row:\n{}".format(top_K.shape,kvalue,top_K))
updates = [0]*len(tensor_1D)
for n in (tf.math.top_k(tensor_1D, k=kvalue, sorted=True, name="topK").indices):  
  updates[n]=tensor_1D[n]
print("final 1D tensor is :-->")
final_tensor=tf.convert_to_tensor(updates)
print(final_tensor)

print("------------------------------------------------------------------------------------------------------------------------------------")

# 2D Tensor (matrix)
tensor_2D = np.array([[50, 100, 300,2990,5],  # row 1
                      [256, 356, 389,200,6],  # row 2
                      [100, 300, 200,200,7], #row 3
                      [1067, 899,100,200,0]])  # row 4
print("input tensor shape is {}".format(tensor_2D.shape))
print("2D Tensor:\n{}".format(tensor_2D))
print("Tensor dimensions: {}".format(tensor_2D.ndim))
kvalue=tensor_2D.shape[0] -1
top_K=tf.math.top_k(tensor_2D, k=kvalue, sorted=True, name="topK").values
print(" new 2D Tensor of shape {} with {} highest values for each row:\n{}".format(top_K.shape,kvalue,top_K))
j=0
updates_final =[]
for n in (tf.math.top_k(tensor_2D, k=kvalue, sorted=True, name="topK").indices):  
  updates = [0]*(tensor_2D.shape[1]) 
  for i in n:    
    updates[i]=tensor_2D[j][i]
  updates_final.append(updates)  
  j=j+1
final_tensor=tf.convert_to_tensor(updates_final)
print("final 2D tensor is :-->")
print(final_tensor)

input tensor shape is (4,)
1D Tensor:
[  50  100  300 2990]
Tensor dimensions: 1
 new 1D Tensor of shape (3,) with 3 highest values for each row:
[2990  300  100]
final 1D tensor is :-->
tf.Tensor([   0  100  300 2990], shape=(4,), dtype=int32)
------------------------------------------------------------------------------------------------------------------------------------
input tensor shape is (4, 5)
2D Tensor:
[[  50  100  300 2990    5]
 [ 256  356  389  200    6]
 [ 100  300  200  200    7]
 [1067  899  100  200    0]]
Tensor dimensions: 2
 new 2D Tensor of shape (4, 3) with 3 highest values for each row:
[[2990  300  100]
 [ 389  356  256]
 [ 300  200  200]
 [1067  899  200]]
final 2D tensor is :-->
tf.Tensor(
[[   0  100  300 2990    0]
 [ 256  356  389    0    0]
 [   0  300  200  200    0]
 [1067  899    0  200    0]], shape=(4, 5), dtype=int32)


### 4)Implement an exponential moving average. That is, given a decay rate a and an input tensor of length T, create a new length T tensor where new[0] = input[0] and new[t] = a * new[t-1] + (1-a) * input[t] otherwise. Do not use tf.train.ExponentialMovingAverage.

In [0]:
a=1.1
T=10
inp = tf.random.uniform([T])

def new_tensor(inp):
  input = inp
  new = np.zeros(T)
  new[0] = input[0]
  for t in range(1,T):
    new[t] = a * new[t-1] + (1.-a) * input[t]
  
  return tf.convert_to_tensor(new)

print(inp)

print(new_tensor(inp))

tf.Tensor(
[0.680709   0.14049423 0.7075566  0.28323436 0.16617465 0.2521243
 0.28247166 0.06483459 0.10741627 0.07048941], shape=(10,), dtype=float32)
tf.Tensor(
[0.680709   0.73473048 0.73744786 0.78286922 0.84453869 0.90378016
 0.96591103 1.05601871 1.15087903 1.25891793], shape=(10,), dtype=float64)


### 5) Find a way to return the last element in 4. without using loops. That is, return new[T] only – you don’t need to compute the other time steps (if you can avoid it)

In [0]:
a=0.5
T=10
inp = tf.random.uniform([T])

def new_tensor(inp):
  input = inp

new_tensor(inp)

### 6)Given three integer tensors x, y, z all of the same (arbitrary) shape, create a new tensor that takes values from y where x is even and from z where x is odd.

In [0]:
import tensorflow as tf
import numpy as np

x=tf.constant([1, 2, 3, 4, 5, 6],dtype=tf.int64)
y=tf.constant([111, 222, 333, 444, 555, 666],dtype=tf.int64)
z=tf.constant([30000, 50000, 70000, 11000, 90000, 13000],dtype=tf.int64)
new=tf.Variable(tf.zeros_like(x) ,dtype=tf.int64)
even=tf.constant(2,dtype=tf.int64)
check=tf.math.floormod(x,even)
comparison = tf.equal( check, tf.constant( 1,dtype=tf.int64 ) )
new.assign( tf.where (comparison,z,y) )
new_tensor=tf.convert_to_tensor(new, dtype=tf.int64)
print(new_tensor)

tf.Tensor([30000   222 70000   444 90000   666], shape=(6,), dtype=int64)


### 7) Given a tensor of arbitrary and unknown shape (but at least one dimension), return 100 if the last dimension has size > 100, 12 if the last dimension has size <= 100 and > 44, and return 0 otherwise.

In [0]:
import tensorflow as tf

def count():
  n= int(input("Enter the dimension:"))
  y=tf.constant(1,shape=(n,n))
  dim=y.ndim
  last_dimension=(tf.shape(y)[dim-1])
  print(last_dimension)
  if last_dimension>100:
    print(100)
    return 100
  elif (last_dimension<=100 and last_dimension > 44):
    print(12)
    return 12
  else:
    print(0)
    return 0
count()

Enter the dimension:300
tf.Tensor(300, shape=(), dtype=int32)
100


100

### 8) As 7., but also create three global counts (integers), where count i should grow by 1 if condition i happened. Run the function from 7. multiple times to test whether your counting works. Now, add a @tf.function decorator to the function from 7. Does your counter still work? If not, why not? Can you change it so it does work?

In [0]:
import tensorflow as tf
x=[0,0,0]


def count(n):  
  y=tf.constant(1,shape=(n,n))
  dim=y.ndim  
  last_dimension=(tf.shape(y)[dim-1])  
  if last_dimension>100:    
    return 0
  elif (last_dimension<=100 and last_dimension > 44):    
    return 1
  else:    
    return 2

input=[19,30,45,99,200,300,400]
for n in input:
  i=count(n)
  x[i]=x[i]+1
print(x)
print("-------------------------------------------------------------")



test=[0,0,0]


def count2(n):  
  y=tf.constant(1,shape=(n,n))  
  dim=2
  last_dimension=(tf.shape(y)[dim-1])  
  if last_dimension>100:    
    test[0]= test[0]+1  
    return 0
  elif (last_dimension<=100 and last_dimension > 44):
    test[1]= test[1]+1    
    return 1
  else: 
    test[2]= test[2]+1   
    return 2

input=[19,30,45,99,200,300,400]
for n in input:
  count2(n)  
print(test)


print("-------------------------------------------------------------")
print('------moved the counter outside the function to resolve the error---- ')
z=[0,0,0]
@tf.function
def count3(n):  
  y=tf.constant(1,shape=(n,n))  
  dim=2
  last_dimension=(tf.shape(y)[dim-1])  
  if last_dimension>100:     
    return 0
  elif (last_dimension<=100 and last_dimension > 44):       
    return 1
  else:     
    return 2

input=[19,30,45,99,200,300,400]
for n in input:
  i=count3(n)
  z[i]=z[i]+1  
print(z)

[3, 2, 2]
-------------------------------------------------------------
[3, 2, 2]
-------------------------------------------------------------
------moved the counter outside the function to resolve the error---- 
[3, 2, 2]


### 9) Given two 1D tensors of equal length n, create a tensor of shape (n, n) where element i,j is the ith element of the first tensor minus the jth element of the second tensor. No loops! Hint: Tensorflow supports broadcasting much like numpy.

In [0]:
import tensorflow as tf

x = tf.constant([1, 2,3])
y = tf.constant([3, 4,3])
if len(x)==len(y):
  n=len(x)
  x_new=tf.reshape(x,shape=(1,n))
  x2 = tf.broadcast_to(tf.transpose(x_new), [n, n])
  y = tf.broadcast_to(y, [n, n])
  new=tf.subtract(x2,y)
  print(new)
else:
  print('ERROR: length miss match')

print('----with decorator------')
# with decorartor
@tf.function
def example():
  x = tf.constant([1, 2,3])
  y = tf.constant([3, 4,3])
  if len(x)==len(y):
    n=len(x)
    x_new=tf.reshape(x,shape=(1,n))
    x2 = tf.broadcast_to(tf.transpose(x_new), [n, n])
    y = tf.broadcast_to(y, [n, n])
    new=tf.subtract(x2,y) 
    return new   
  else:
    return 'ERROR: length miss match'
  
example()

tf.Tensor(
[[-2 -3 -2]
 [-1 -2 -1]
 [ 0 -1  0]], shape=(3, 3), dtype=int32)
----with decorator------


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-2, -3, -2],
       [-1, -2, -1],
       [ 0, -1,  0]], dtype=int32)>

### 10) Implement dot product attention: You are given a sequence of encoder states h of shape batch x time x features and the last decoder state s of shape batch x features. Compute the attention weights alpha where alpha[:, i] is equal to h[:, i] * s where * is the dot product between vectors (in this case we also have a batch dimension so the dot product should be between the corresponding vectors within the batch). That is, alpha should be of shape batch x time and alpha[:, i] should contain the attention weights for encoder time step i.

In [0]:
import tensorflow as tf
import numpy as np

batch=10
time=5
features=3


initializer = tf.keras.initializers.GlorotUniform
h=tf.Variable(initializer()([batch,time,features]))
s=tf.Variable(initializer()([batch,features]))
s=tf.transpose(s)
alpha=tf.Variable(tf.zeros([batch,time]))
for time_step in tf.range(tf.shape(alpha)[1]):        
    m=tf.matmul(h[:,time_step,:],s) 
    sum= tf.reduce_sum(m,1)
    alpha[:,time_step].assign(sum) 
    probability=tf.nn.softmax(alpha).numpy()[0]    
    p=0
    for i in probability:
      p=p+i          
    print("Attention weights alpha for encoder time step {}: \n {}".format(time_step,alpha[:,time_step]))
    print("Total Probability for attention weight alpha at time step {} is {} ".format(time_step ,round(p,4)))
    print("-------------------------------------------------------------------------------------------------")
print('Final alpha is :')
print(alpha)

Attention weights alpha for encoder time step 0: 
 [-0.01552661  0.0235538   0.16825335  0.4927227   0.40647098 -0.1179717
  0.07458105  0.03931569  0.3969359   0.3678209 ]
Total Probability for attention weight alpha at time step 0 is 1.0 
-------------------------------------------------------------------------------------------------
Attention weights alpha for encoder time step 1: 
 [ 0.3961097   0.5748293   0.35734907 -0.46502495 -0.2097977  -0.21193908
 -0.20779058  0.70661074  0.0686395   0.05519234]
Total Probability for attention weight alpha at time step 1 is 1.0 
-------------------------------------------------------------------------------------------------
Attention weights alpha for encoder time step 2: 
 [-0.49231014  0.1933679   0.01701897  0.5053459   0.14219755  0.11136153
 -0.4771728   0.2734328  -0.48951578 -0.39408368]
Total Probability for attention weight alpha at time step 2 is 1.0 
-------------------------------------------------------------------------------